In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/DontGetKicked/example_entry.csv
/kaggle/input/DontGetKicked/training.zip
/kaggle/input/DontGetKicked/Carvana_Data_Dictionary.txt
/kaggle/input/DontGetKicked/test.zip
/kaggle/input/DontGetKicked/training.csv
/kaggle/input/DontGetKicked/test.csv

In [2]:
pd.options.display.max_columns  = 35
# 모든 column들이 보일 수 있게 설정

In [3]:
# 중고차 거래 - 해당 가격이 정상적인 가격인지 분류하는 대회

train = pd.read_csv("/kaggle/input/DontGetKicked/training.csv")
test = pd.read_csv("/kaggle/input/DontGetKicked/test.csv")

# train, test 한 번에 출력
display(train, test)

,RefId,IsBadBuy,PurchDate,Auction,VehYear,VehicleAge,Make,Model,Trim,SubModel,Color,Transmission,WheelTypeID,WheelType,VehOdo,Nationality,Size,TopThreeAmericanName,MMRAcquisitionAuctionAveragePrice,MMRAcquisitionAuctionCleanPrice,MMRAcquisitionRetailAveragePrice,MMRAcquisitonRetailCleanPrice,MMRCurrentAuctionAveragePrice,MMRCurrentAuctionCleanPrice,MMRCurrentRetailAveragePrice,MMRCurrentRetailCleanPrice,PRIMEUNIT,AUCGUART,BYRNO,VNZIP1,VNST,VehBCost,IsOnlineSale,WarrantyCost
0,1,0,12/7/2009,ADESA,2006,3,MAZDA,MAZDA3,i,4D SEDAN I,RED,AUTO,1.0,Alloy,89046,OTHER ASIAN,MEDIUM,OTHER,8155.0,9829.0,11636.0,13600.0,7451.0,8552.0,11597.0,12409.0,NaN,NaN,21973,33619,FL,7100.0,0,1113
1,2,0,12/7/2009,ADESA,2004,5,DODGE,1500 RAM PICKUP 2WD,ST,QUAD CAB 4.7L SLT,WHITE,AUTO,1.0,Alloy,93593,AMERICAN,LARGE TRUCK,CHRYSLER,6854.0,8383.0,10897.0,12572.0,7456.0,9222.0,11374.0,12791.0,NaN,NaN,19638,33619,FL,7600.0,0,1053
2,3,0,12/7/2009,ADESA,2005,4,DODGE,STRATUS V6,SXT,4D SEDAN SXT FFV,MAROON,AUTO,2.0,Covers,73807,AMERICAN,MEDIUM,CHRYSLER,3202.0,4760.0,6943.0,8457.0,4035.0,5557.0,7146.0,8702.0,NaN,NaN,19638,33619,FL,4900.0,0,1389
3,4,0,12/7/2009,ADESA,2004,5,DODGE,NEON,SXT,4D SEDAN,SILVER,AUTO,1.0,Alloy,65617,AMERICAN,COMPACT,CHRYSLER,1893.0,2675.0,4658.0,5690.0,1844.0,2646.0,4375.0,5518.0,NaN,NaN,19638,33619,FL,4100.0,0,630
4,5,0,12/7/2009,ADESA,2005,4,FORD,FOCUS,ZX3,2D COUPE ZX3,SILVER,MANUAL,2.0,Covers,69367,AMERICAN,COMPACT,FORD,3913.0,5054.0,7723.0,8707.0,3247.0,4384.0,6739.0,7911.0,NaN,NaN,19638,33619,FL,4000.0,0,1020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72978,73010,1,12/2/2009,ADESA,2001,8,MERCURY,SABLE,GS,4D SEDAN GS,BLACK,AUTO,1.0,Alloy,45234,AMERICAN,MEDIUM,FORD,1996.0,2993.0,2656.0,3732.0,2190.0,3055.0,4836.0,5937.0,NaN,NaN,18111,30212,GA,4200.0,0,993
72979,73011,0,12/2/2009,ADESA,2007,2,CHEVROLET,MALIBU 4C,LS,4D SEDAN LS,SILVER,AUTO,NaN,NaN,71759,AMERICAN,MEDIUM,GM,6418.0,7325.0,7431.0,8411.0,6785.0,8132.0,10151.0,11652.0,NaN,NaN,18881,30212,GA,6200.0,0,1038
72980,73012,0,12/2/2009,ADESA,2005,4,JEEP,GRAND CHEROKEE 2WD V,Lar,4D WAGON LAREDO,SILVER,AUTO,1.0,Alloy,88500,AMERICAN,MEDIUM SUV,CHRYSLER,8545.0,9959.0,9729.0,11256.0,8375.0,9802.0,11831.0,14402.0,NaN,NaN,18111,30212,GA,8200.0,0,1893
72981,73013,0,12/2/2009,ADESA,2006,3,CHEVROLET,IMPALA,LS,4D SEDAN LS,WHITE,AUTO,1.0,Alloy,79554,AMERICAN,LARGE,GM,6420.0,7604.0,7434.0,8712.0,6590.0,7684.0,10099.0,11228.0,NaN,NaN,18881,30212,GA,7000.0,0,1974
72982,73014,0,12/2/2009,ADESA,2006,3,MAZDA,MAZDA6,s,4D SEDAN S,SILVER,AUTO,1.0,Alloy,66855,OTHER ASIAN,MEDIUM,OTHER,7535.0,8771.0,8638.0,9973.0,7730.0,9102.0,11954.0,13246.0,NaN,NaN,18111,30212,GA,8000.0,0,1313

,RefId,PurchDate,Auction,VehYear,VehicleAge,Make,Model,Trim,SubModel,Color,Transmission,WheelTypeID,WheelType,VehOdo,Nationality,Size,TopThreeAmericanName,MMRAcquisitionAuctionAveragePrice,MMRAcquisitionAuctionCleanPrice,MMRAcquisitionRetailAveragePrice,MMRAcquisitonRetailCleanPrice,MMRCurrentAuctionAveragePrice,MMRCurrentAuctionCleanPrice,MMRCurrentRetailAveragePrice,MMRCurrentRetailCleanPrice,PRIMEUNIT,AUCGUART,BYRNO,VNZIP1,VNST,VehBCost,IsOnlineSale,WarrantyCost
0,73015,12/2/2009,ADESA,2005,4,PONTIAC,GRAND PRIX,Bas,4D SEDAN,SILVER,AUTO,1.0,Alloy,85377,AMERICAN,LARGE,GM,5032.0,6386.0,5935.0,7397.0,4905.0,6181.0,8557.0,9752.0,NaN,NaN,18881,30212,GA,6500.0,0,2152
1,73016,12/2/2009,ADESA,2005,4,CHEVROLET,MALIBU V6,LS,4D SEDAN LS,SILVER,AUTO,1.0,Alloy,61873,AMERICAN,MEDIUM,GM,4502.0,5685.0,5362.0,6640.0,4645.0,5710.0,7562.0,9296.0,NaN,NaN,18111,30212,GA,6300.0,0,1118
2,73017,12/2/2009,ADESA,2006,3,DODGE,DURANGO 2WD V8,Adv,4D SUV 4.7L ADVENTURER,SILVER,AUTO,1.0,Alloy,69283,AMERICAN,MEDIUM SUV,CHRYSLER,10244.0,13041.0,11564.0,14584.0,10883.0,12166.0,15340.0,16512.0,NaN,NaN,18111,30212,GA,9700.0,0,1215
3,73018,12/2/2009,ADESA,2002,7,SATURN,L SERIES,L20,4D SEDAN L200,GOLD,AUTO,1.0,Alloy,87889,AMERICAN,MEDIUM,GM,2558.0,3542.0,3263.0,4325.0,2928.0,3607.0,5725.0,6398.0,NaN,NaN,18881,30212,GA,4150.0,0,1933
4,73019,12/2/2009,ADESA,2007,2,HYUNDAI,ACCENT,GS,2D COUPE GS,BLUE,AUTO,NaN,NaN,73432,OTHER ASIAN,COMPACT,OTHER,5013.0,6343.0,5914.0,7350.0,5013.0,6343.0,5914.0,7350.0,NaN,NaN,18111,30212,GA,4100.0,0,920
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48702,121742,11/17/2010,MANHEIM,2005,5,FORD,FIVE HUNDRED,SEL,4D SEDAN SEL,BLACK,AUTO,1.0,Alloy,88645,AMERICAN,LARGE,FORD,5358.0,6836.0,8987.0,10905.0,5761.0,6965.0,9764.0,11395.0,NaN,NaN,20928,33411,FL,7955.0,0,1633
48703,121743,11/17/2010,MANHEIM,2007,3,TOYOTA,COROLLA,CE,4D SEDAN CE,GREEN,AUTO,2.0,Covers,81862,TOP LINE ASIAN,COMPACT,OTHER,6849.0,7992.0,10999.0,12021.0,6856.0,8183.0,10283.0,11565.0,NaN,NaN,20928,33411,FL,7035.0,0,594
48704,121744,11/17/2010,MANHEIM,2006,4,KIA,SPECTRA,EX,4D SEDAN EX,BLACK,AUTO,2.0,Covers,82451,OTHER ASIAN,MEDIUM,OTHER,4662.0,5655.0,7972.0,9670.0,4833.0,5856.0,7871.0,9490.0,NO,GREEN,20928,33411,FL,6335.0,0,594
48705,121745,11/17/2010,MANHEIM,2005,5,MAZDA,MAZDA3,s,4D SEDAN GT,SILVER,AUTO,1.0,Alloy,75760,OTHER ASIAN,MEDIUM,OTHER,5953.0,8166.0,9137.0,11949.0,5092.0,6853.0,8576.0,9937.0,NO,GREEN,20928,33411,FL,8055.0,0,1038
48706,121746,11/17/2010,MANHEIM,2003,7,BUICK,RENDEZVOUS AWD,CX,4D SUV CX,GOLD,AUTO,2.0,Covers,82174,AMERICAN,MEDIUM SUV,GM,3269.0,4435.0,6893.0,8221.0,4526.0,5761.0,8266.0,9388.0,NO,GREEN,20928,33411,FL,7755.0,0,5392

- 문자열 데이터 있음
- column들이 다 보이지 않음 -> max_columns 설정
- 결측치 있음`
- 분류 문제

In [4]:
# axis = 0: 데이터 방향으로 합침 (위아래)
# axis = 1: 데이터 양옆으로 합쳐짐 
alldata = pd.concat([train, test], axis = 0) 
alldata
# train test 합치면 전처리 1번만 하면 됨
# test 데이터 부분의 정답 column 'IsBadBuy' test 데이터 부분에도 새롭게 생성, none 값으로 설정

,RefId,IsBadBuy,PurchDate,Auction,VehYear,VehicleAge,Make,Model,Trim,SubModel,Color,Transmission,WheelTypeID,WheelType,VehOdo,Nationality,Size,TopThreeAmericanName,MMRAcquisitionAuctionAveragePrice,MMRAcquisitionAuctionCleanPrice,MMRAcquisitionRetailAveragePrice,MMRAcquisitonRetailCleanPrice,MMRCurrentAuctionAveragePrice,MMRCurrentAuctionCleanPrice,MMRCurrentRetailAveragePrice,MMRCurrentRetailCleanPrice,PRIMEUNIT,AUCGUART,BYRNO,VNZIP1,VNST,VehBCost,IsOnlineSale,WarrantyCost
0,1,0.0,12/7/2009,ADESA,2006,3,MAZDA,MAZDA3,i,4D SEDAN I,RED,AUTO,1.0,Alloy,89046,OTHER ASIAN,MEDIUM,OTHER,8155.0,9829.0,11636.0,13600.0,7451.0,8552.0,11597.0,12409.0,NaN,NaN,21973,33619,FL,7100.0,0,1113
1,2,0.0,12/7/2009,ADESA,2004,5,DODGE,1500 RAM PICKUP 2WD,ST,QUAD CAB 4.7L SLT,WHITE,AUTO,1.0,Alloy,93593,AMERICAN,LARGE TRUCK,CHRYSLER,6854.0,8383.0,10897.0,12572.0,7456.0,9222.0,11374.0,12791.0,NaN,NaN,19638,33619,FL,7600.0,0,1053
2,3,0.0,12/7/2009,ADESA,2005,4,DODGE,STRATUS V6,SXT,4D SEDAN SXT FFV,MAROON,AUTO,2.0,Covers,73807,AMERICAN,MEDIUM,CHRYSLER,3202.0,4760.0,6943.0,8457.0,4035.0,5557.0,7146.0,8702.0,NaN,NaN,19638,33619,FL,4900.0,0,1389
3,4,0.0,12/7/2009,ADESA,2004,5,DODGE,NEON,SXT,4D SEDAN,SILVER,AUTO,1.0,Alloy,65617,AMERICAN,COMPACT,CHRYSLER,1893.0,2675.0,4658.0,5690.0,1844.0,2646.0,4375.0,5518.0,NaN,NaN,19638,33619,FL,4100.0,0,630
4,5,0.0,12/7/2009,ADESA,2005,4,FORD,FOCUS,ZX3,2D COUPE ZX3,SILVER,MANUAL,2.0,Covers,69367,AMERICAN,COMPACT,FORD,3913.0,5054.0,7723.0,8707.0,3247.0,4384.0,6739.0,7911.0,NaN,NaN,19638,33619,FL,4000.0,0,1020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48702,121742,NaN,11/17/2010,MANHEIM,2005,5,FORD,FIVE HUNDRED,SEL,4D SEDAN SEL,BLACK,AUTO,1.0,Alloy,88645,AMERICAN,LARGE,FORD,5358.0,6836.0,8987.0,10905.0,5761.0,6965.0,9764.0,11395.0,NaN,NaN,20928,33411,FL,7955.0,0,1633
48703,121743,NaN,11/17/2010,MANHEIM,2007,3,TOYOTA,COROLLA,CE,4D SEDAN CE,GREEN,AUTO,2.0,Covers,81862,TOP LINE ASIAN,COMPACT,OTHER,6849.0,7992.0,10999.0,12021.0,6856.0,8183.0,10283.0,11565.0,NaN,NaN,20928,33411,FL,7035.0,0,594
48704,121744,NaN,11/17/2010,MANHEIM,2006,4,KIA,SPECTRA,EX,4D SEDAN EX,BLACK,AUTO,2.0,Covers,82451,OTHER ASIAN,MEDIUM,OTHER,4662.0,5655.0,7972.0,9670.0,4833.0,5856.0,7871.0,9490.0,NO,GREEN,20928,33411,FL,6335.0,0,594
48705,121745,NaN,11/17/2010,MANHEIM,2005,5,MAZDA,MAZDA3,s,4D SEDAN GT,SILVER,AUTO,1.0,Alloy,75760,OTHER ASIAN,MEDIUM,OTHER,5953.0,8166.0,9137.0,11949.0,5092.0,6853.0,8576.0,9937.0,NO,GREEN,20928,33411,FL,8055.0,0,1038
48706,121746,NaN,11/17/2010,MANHEIM,2003,7,BUICK,RENDEZVOUS AWD,CX,4D SUV CX,GOLD,AUTO,2.0,Covers,82174,AMERICAN,MEDIUM SUV,GM,3269.0,4435.0,6893.0,8221.0,4526.0,5761.0,8266.0,9388.0,NO,GREEN,20928,33411,FL,7755.0,0,5392

In [5]:
# RefId : id column 
# IsBadBuy : 정답 column 지우기
# PurcDate : 날짜 column 학습 불가 -> 지우기
alldata2 = alldata.drop(columns = ['RefId', 'IsBadBuy', 'PurchDate']) 
alldata2

,Auction,VehYear,VehicleAge,Make,Model,Trim,SubModel,Color,Transmission,WheelTypeID,WheelType,VehOdo,Nationality,Size,TopThreeAmericanName,MMRAcquisitionAuctionAveragePrice,MMRAcquisitionAuctionCleanPrice,MMRAcquisitionRetailAveragePrice,MMRAcquisitonRetailCleanPrice,MMRCurrentAuctionAveragePrice,MMRCurrentAuctionCleanPrice,MMRCurrentRetailAveragePrice,MMRCurrentRetailCleanPrice,PRIMEUNIT,AUCGUART,BYRNO,VNZIP1,VNST,VehBCost,IsOnlineSale,WarrantyCost
0,ADESA,2006,3,MAZDA,MAZDA3,i,4D SEDAN I,RED,AUTO,1.0,Alloy,89046,OTHER ASIAN,MEDIUM,OTHER,8155.0,9829.0,11636.0,13600.0,7451.0,8552.0,11597.0,12409.0,NaN,NaN,21973,33619,FL,7100.0,0,1113
1,ADESA,2004,5,DODGE,1500 RAM PICKUP 2WD,ST,QUAD CAB 4.7L SLT,WHITE,AUTO,1.0,Alloy,93593,AMERICAN,LARGE TRUCK,CHRYSLER,6854.0,8383.0,10897.0,12572.0,7456.0,9222.0,11374.0,12791.0,NaN,NaN,19638,33619,FL,7600.0,0,1053
2,ADESA,2005,4,DODGE,STRATUS V6,SXT,4D SEDAN SXT FFV,MAROON,AUTO,2.0,Covers,73807,AMERICAN,MEDIUM,CHRYSLER,3202.0,4760.0,6943.0,8457.0,4035.0,5557.0,7146.0,8702.0,NaN,NaN,19638,33619,FL,4900.0,0,1389
3,ADESA,2004,5,DODGE,NEON,SXT,4D SEDAN,SILVER,AUTO,1.0,Alloy,65617,AMERICAN,COMPACT,CHRYSLER,1893.0,2675.0,4658.0,5690.0,1844.0,2646.0,4375.0,5518.0,NaN,NaN,19638,33619,FL,4100.0,0,630
4,ADESA,2005,4,FORD,FOCUS,ZX3,2D COUPE ZX3,SILVER,MANUAL,2.0,Covers,69367,AMERICAN,COMPACT,FORD,3913.0,5054.0,7723.0,8707.0,3247.0,4384.0,6739.0,7911.0,NaN,NaN,19638,33619,FL,4000.0,0,1020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48702,MANHEIM,2005,5,FORD,FIVE HUNDRED,SEL,4D SEDAN SEL,BLACK,AUTO,1.0,Alloy,88645,AMERICAN,LARGE,FORD,5358.0,6836.0,8987.0,10905.0,5761.0,6965.0,9764.0,11395.0,NaN,NaN,20928,33411,FL,7955.0,0,1633
48703,MANHEIM,2007,3,TOYOTA,COROLLA,CE,4D SEDAN CE,GREEN,AUTO,2.0,Covers,81862,TOP LINE ASIAN,COMPACT,OTHER,6849.0,7992.0,10999.0,12021.0,6856.0,8183.0,10283.0,11565.0,NaN,NaN,20928,33411,FL,7035.0,0,594
48704,MANHEIM,2006,4,KIA,SPECTRA,EX,4D SEDAN EX,BLACK,AUTO,2.0,Covers,82451,OTHER ASIAN,MEDIUM,OTHER,4662.0,5655.0,7972.0,9670.0,4833.0,5856.0,7871.0,9490.0,NO,GREEN,20928,33411,FL,6335.0,0,594
48705,MANHEIM,2005,5,MAZDA,MAZDA3,s,4D SEDAN GT,SILVER,AUTO,1.0,Alloy,75760,OTHER ASIAN,MEDIUM,OTHER,5953.0,8166.0,9137.0,11949.0,5092.0,6853.0,8576.0,9937.0,NO,GREEN,20928,33411,FL,8055.0,0,1038
48706,MANHEIM,2003,7,BUICK,RENDEZVOUS AWD,CX,4D SUV CX,GOLD,AUTO,2.0,Covers,82174,AMERICAN,MEDIUM SUV,GM,3269.0,4435.0,6893.0,8221.0,4526.0,5761.0,8266.0,9388.0,NO,GREEN,20928,33411,FL,7755.0,0,5392

In [6]:
## categorical 변수 바꾸어주기(문자 column 숫자로)
alldata2['Auction'].unique() # Auction column에 무슨 카테고리가 있는지 확인

array(['ADESA', 'OTHER', 'MANHEIM'], dtype=object)

In [7]:
# 무엇을 무엇으로 바꿀 때: dictionary {} 형식 활용
alldata2['Auction'] = alldata2['Auction'].replace({'ADESA':0, 'OTHER':1, 'MANHEIM':2})
alldata2 #Auction 잘 바뀐 것 확인할 수 있음

,Auction,VehYear,VehicleAge,Make,Model,Trim,SubModel,Color,Transmission,WheelTypeID,WheelType,VehOdo,Nationality,Size,TopThreeAmericanName,MMRAcquisitionAuctionAveragePrice,MMRAcquisitionAuctionCleanPrice,MMRAcquisitionRetailAveragePrice,MMRAcquisitonRetailCleanPrice,MMRCurrentAuctionAveragePrice,MMRCurrentAuctionCleanPrice,MMRCurrentRetailAveragePrice,MMRCurrentRetailCleanPrice,PRIMEUNIT,AUCGUART,BYRNO,VNZIP1,VNST,VehBCost,IsOnlineSale,WarrantyCost
0,0,2006,3,MAZDA,MAZDA3,i,4D SEDAN I,RED,AUTO,1.0,Alloy,89046,OTHER ASIAN,MEDIUM,OTHER,8155.0,9829.0,11636.0,13600.0,7451.0,8552.0,11597.0,12409.0,NaN,NaN,21973,33619,FL,7100.0,0,1113
1,0,2004,5,DODGE,1500 RAM PICKUP 2WD,ST,QUAD CAB 4.7L SLT,WHITE,AUTO,1.0,Alloy,93593,AMERICAN,LARGE TRUCK,CHRYSLER,6854.0,8383.0,10897.0,12572.0,7456.0,9222.0,11374.0,12791.0,NaN,NaN,19638,33619,FL,7600.0,0,1053
2,0,2005,4,DODGE,STRATUS V6,SXT,4D SEDAN SXT FFV,MAROON,AUTO,2.0,Covers,73807,AMERICAN,MEDIUM,CHRYSLER,3202.0,4760.0,6943.0,8457.0,4035.0,5557.0,7146.0,8702.0,NaN,NaN,19638,33619,FL,4900.0,0,1389
3,0,2004,5,DODGE,NEON,SXT,4D SEDAN,SILVER,AUTO,1.0,Alloy,65617,AMERICAN,COMPACT,CHRYSLER,1893.0,2675.0,4658.0,5690.0,1844.0,2646.0,4375.0,5518.0,NaN,NaN,19638,33619,FL,4100.0,0,630
4,0,2005,4,FORD,FOCUS,ZX3,2D COUPE ZX3,SILVER,MANUAL,2.0,Covers,69367,AMERICAN,COMPACT,FORD,3913.0,5054.0,7723.0,8707.0,3247.0,4384.0,6739.0,7911.0,NaN,NaN,19638,33619,FL,4000.0,0,1020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48702,2,2005,5,FORD,FIVE HUNDRED,SEL,4D SEDAN SEL,BLACK,AUTO,1.0,Alloy,88645,AMERICAN,LARGE,FORD,5358.0,6836.0,8987.0,10905.0,5761.0,6965.0,9764.0,11395.0,NaN,NaN,20928,33411,FL,7955.0,0,1633
48703,2,2007,3,TOYOTA,COROLLA,CE,4D SEDAN CE,GREEN,AUTO,2.0,Covers,81862,TOP LINE ASIAN,COMPACT,OTHER,6849.0,7992.0,10999.0,12021.0,6856.0,8183.0,10283.0,11565.0,NaN,NaN,20928,33411,FL,7035.0,0,594
48704,2,2006,4,KIA,SPECTRA,EX,4D SEDAN EX,BLACK,AUTO,2.0,Covers,82451,OTHER ASIAN,MEDIUM,OTHER,4662.0,5655.0,7972.0,9670.0,4833.0,5856.0,7871.0,9490.0,NO,GREEN,20928,33411,FL,6335.0,0,594
48705,2,2005,5,MAZDA,MAZDA3,s,4D SEDAN GT,SILVER,AUTO,1.0,Alloy,75760,OTHER ASIAN,MEDIUM,OTHER,5953.0,8166.0,9137.0,11949.0,5092.0,6853.0,8576.0,9937.0,NO,GREEN,20928,33411,FL,8055.0,0,1038
48706,2,2003,7,BUICK,RENDEZVOUS AWD,CX,4D SUV CX,GOLD,AUTO,2.0,Covers,82174,AMERICAN,MEDIUM SUV,GM,3269.0,4435.0,6893.0,8221.0,4526.0,5761.0,8266.0,9388.0,NO,GREEN,20928,33411,FL,7755.0,0,5392

In [8]:
alldata['Make'].unique() # 종류가 너무 많음 -> 자동으로 바꾸는 것 있었으면 좋겠다

array(['MAZDA', 'DODGE', 'FORD', 'MITSUBISHI', 'KIA', 'GMC', 'NISSAN',
       'CHEVROLET', 'SATURN', 'CHRYSLER', 'MERCURY', 'HYUNDAI', 'TOYOTA',
       'PONTIAC', 'SUZUKI', 'JEEP', 'HONDA', 'OLDSMOBILE', 'BUICK',
       'SCION', 'VOLKSWAGEN', 'ISUZU', 'LINCOLN', 'MINI', 'SUBARU',
       'CADILLAC', 'VOLVO', 'INFINITI', 'PLYMOUTH', 'LEXUS', 'ACURA',
       'TOYOTA SCION', 'HUMMER'], dtype=object)

Encoding(인코딩): 문자를 숫자로 바꾸는 과정     
LabelEncoder 라이브러리 가져와서 처리하기   
    1. 어떤 값에 숫자를 등록하겠다 >> fit       
    2. 실제로 등록된 것 바탕으로 변환  >> transform     
fit_transform: 등록과 함게 변환

In [9]:
# 전처리중 >> preprocessing
from sklearn.preprocessing import LabelEncoder 

# 각 category 안의 값들을 알파벳 순서로 정렬, 순서대로 값 부여
le = LabelEncoder() #Label Encoder 함수 정의하기
alldata2['Make'] = le.fit_transform(alldata2['Make'])
alldata2 # Make column int 형으로 변환됨

,Auction,VehYear,VehicleAge,Make,Model,Trim,SubModel,Color,Transmission,WheelTypeID,WheelType,VehOdo,Nationality,Size,TopThreeAmericanName,MMRAcquisitionAuctionAveragePrice,MMRAcquisitionAuctionCleanPrice,MMRAcquisitionRetailAveragePrice,MMRAcquisitonRetailCleanPrice,MMRCurrentAuctionAveragePrice,MMRCurrentAuctionCleanPrice,MMRCurrentRetailAveragePrice,MMRCurrentRetailCleanPrice,PRIMEUNIT,AUCGUART,BYRNO,VNZIP1,VNST,VehBCost,IsOnlineSale,WarrantyCost
0,0,2006,3,17,MAZDA3,i,4D SEDAN I,RED,AUTO,1.0,Alloy,89046,OTHER ASIAN,MEDIUM,OTHER,8155.0,9829.0,11636.0,13600.0,7451.0,8552.0,11597.0,12409.0,NaN,NaN,21973,33619,FL,7100.0,0,1113
1,0,2004,5,5,1500 RAM PICKUP 2WD,ST,QUAD CAB 4.7L SLT,WHITE,AUTO,1.0,Alloy,93593,AMERICAN,LARGE TRUCK,CHRYSLER,6854.0,8383.0,10897.0,12572.0,7456.0,9222.0,11374.0,12791.0,NaN,NaN,19638,33619,FL,7600.0,0,1053
2,0,2005,4,5,STRATUS V6,SXT,4D SEDAN SXT FFV,MAROON,AUTO,2.0,Covers,73807,AMERICAN,MEDIUM,CHRYSLER,3202.0,4760.0,6943.0,8457.0,4035.0,5557.0,7146.0,8702.0,NaN,NaN,19638,33619,FL,4900.0,0,1389
3,0,2004,5,5,NEON,SXT,4D SEDAN,SILVER,AUTO,1.0,Alloy,65617,AMERICAN,COMPACT,CHRYSLER,1893.0,2675.0,4658.0,5690.0,1844.0,2646.0,4375.0,5518.0,NaN,NaN,19638,33619,FL,4100.0,0,630
4,0,2005,4,6,FOCUS,ZX3,2D COUPE ZX3,SILVER,MANUAL,2.0,Covers,69367,AMERICAN,COMPACT,FORD,3913.0,5054.0,7723.0,8707.0,3247.0,4384.0,6739.0,7911.0,NaN,NaN,19638,33619,FL,4000.0,0,1020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48702,2,2005,5,6,FIVE HUNDRED,SEL,4D SEDAN SEL,BLACK,AUTO,1.0,Alloy,88645,AMERICAN,LARGE,FORD,5358.0,6836.0,8987.0,10905.0,5761.0,6965.0,9764.0,11395.0,NaN,NaN,20928,33411,FL,7955.0,0,1633
48703,2,2007,3,29,COROLLA,CE,4D SEDAN CE,GREEN,AUTO,2.0,Covers,81862,TOP LINE ASIAN,COMPACT,OTHER,6849.0,7992.0,10999.0,12021.0,6856.0,8183.0,10283.0,11565.0,NaN,NaN,20928,33411,FL,7035.0,0,594
48704,2,2006,4,14,SPECTRA,EX,4D SEDAN EX,BLACK,AUTO,2.0,Covers,82451,OTHER ASIAN,MEDIUM,OTHER,4662.0,5655.0,7972.0,9670.0,4833.0,5856.0,7871.0,9490.0,NO,GREEN,20928,33411,FL,6335.0,0,594
48705,2,2005,5,17,MAZDA3,s,4D SEDAN GT,SILVER,AUTO,1.0,Alloy,75760,OTHER ASIAN,MEDIUM,OTHER,5953.0,8166.0,9137.0,11949.0,5092.0,6853.0,8576.0,9937.0,NO,GREEN,20928,33411,FL,8055.0,0,1038
48706,2,2003,7,1,RENDEZVOUS AWD,CX,4D SUV CX,GOLD,AUTO,2.0,Covers,82174,AMERICAN,MEDIUM SUV,GM,3269.0,4435.0,6893.0,8221.0,4526.0,5761.0,8266.0,9388.0,NO,GREEN,20928,33411,FL,7755.0,0,5392

In [10]:
le.classes_ # Label Encoder의 classes 번호 부여 기준 (알파벳 순서대로 0부터)
# 트리 모델 -> 어떤 column이 카테고리적 변수인지 알아서 처리
# One Hot Encoding 시키면 column 너무 많아짐 (KNN 같은 경우는 해줘야 함)

array(['ACURA', 'BUICK', 'CADILLAC', 'CHEVROLET', 'CHRYSLER', 'DODGE',
       'FORD', 'GMC', 'HONDA', 'HUMMER', 'HYUNDAI', 'INFINITI', 'ISUZU',
       'JEEP', 'KIA', 'LEXUS', 'LINCOLN', 'MAZDA', 'MERCURY', 'MINI',
       'MITSUBISHI', 'NISSAN', 'OLDSMOBILE', 'PLYMOUTH', 'PONTIAC',
       'SATURN', 'SCION', 'SUBARU', 'SUZUKI', 'TOYOTA', 'TOYOTA SCION',
       'VOLKSWAGEN', 'VOLVO'], dtype=object)

In [11]:
alldata2.dtypes ==object

Auction                              False
VehYear                              False
VehicleAge                           False
Make                                 False
Model                                 True
Trim                                  True
SubModel                              True
Color                                 True
Transmission                          True
WheelTypeID                          False
WheelType                             True
VehOdo                               False
Nationality                           True
Size                                  True
TopThreeAmericanName                  True
MMRAcquisitionAuctionAveragePrice    False
MMRAcquisitionAuctionCleanPrice      False
MMRAcquisitionRetailAveragePrice     False
MMRAcquisitonRetailCleanPrice        False
MMRCurrentAuctionAveragePrice        False
MMRCurrentAuctionCleanPrice          False
MMRCurrentRetailAveragePrice         False
MMRCurrentRetailCleanPrice           False
PRIMEUNIT                             True
AUCGUART                              True
BYRNO                                False
VNZIP1                               False
VNST                                  True
VehBCost                             False
IsOnlineSale                         False
WarrantyCost                         False
dtype: bool

In [12]:
# 문자형 column에 대해 label encoding 해주기 -> for 문으로 한꺼번에 처리
# 
# 전체 column 중 categorical 변수들만 접근
# type int, float 아닌 columns들
cat = alldata2.columns[alldata2.dtypes ==object] # column 중 데이터타입이 object인 것들만
cat

Index(['Model', 'Trim', 'SubModel', 'Color', 'Transmission', 'WheelType',
       'Nationality', 'Size', 'TopThreeAmericanName', 'PRIMEUNIT', 'AUCGUART',
       'VNST'],
      dtype='object')

In [13]:
for col in cat:
#     print(col)
    alldata2[col] = le.fit_transform(alldata2[col]) # 각 column 돌아가면서 encode
alldata2

,Auction,VehYear,VehicleAge,Make,Model,Trim,SubModel,Color,Transmission,WheelTypeID,WheelType,VehOdo,Nationality,Size,TopThreeAmericanName,MMRAcquisitionAuctionAveragePrice,MMRAcquisitionAuctionCleanPrice,MMRAcquisitionRetailAveragePrice,MMRAcquisitonRetailCleanPrice,MMRCurrentAuctionAveragePrice,MMRCurrentAuctionCleanPrice,MMRCurrentRetailAveragePrice,MMRCurrentRetailCleanPrice,PRIMEUNIT,AUCGUART,BYRNO,VNZIP1,VNST,VehBCost,IsOnlineSale,WarrantyCost
0,0,2006,3,17,620,135,236,13,0,1.0,0,89046,2,5,3,8155.0,9829.0,11636.0,13600.0,7451.0,8552.0,11597.0,12409.0,2,2,21973,33619,5,7100.0,0,1113
1,0,2004,5,5,0,94,826,15,0,1.0,0,93593,0,4,0,6854.0,8383.0,10897.0,12572.0,7456.0,9222.0,11374.0,12791.0,2,2,19638,33619,5,7600.0,0,1053
2,0,2005,4,5,938,99,311,7,0,2.0,1,73807,0,5,0,3202.0,4760.0,6943.0,8457.0,4035.0,5557.0,7146.0,8702.0,2,2,19638,33619,5,4900.0,0,1389
3,0,2004,5,5,700,99,165,14,0,1.0,0,65617,0,0,0,1893.0,2675.0,4658.0,5690.0,1844.0,2646.0,4375.0,5518.0,2,2,19638,33619,5,4100.0,0,630
4,0,2005,4,6,389,129,55,14,1,2.0,1,69367,0,0,1,3913.0,5054.0,7723.0,8707.0,3247.0,4384.0,6739.0,7911.0,2,2,19638,33619,5,4000.0,0,1020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48702,2,2005,5,6,386,85,292,1,0,1.0,0,88645,0,2,1,5358.0,6836.0,8987.0,10905.0,5761.0,6965.0,9764.0,11395.0,2,2,20928,33411,5,7955.0,0,1633
48703,2,2007,3,29,241,9,198,5,0,2.0,1,81862,3,0,3,6849.0,7992.0,10999.0,12021.0,6856.0,8183.0,10283.0,11565.0,2,2,20928,33411,5,7035.0,0,594
48704,2,2006,4,14,912,23,210,1,0,2.0,1,82451,2,5,3,4662.0,5655.0,7972.0,9670.0,4833.0,5856.0,7871.0,9490.0,0,0,20928,33411,5,6335.0,0,594
48705,2,2005,5,17,620,136,223,14,0,1.0,0,75760,2,5,3,5953.0,8166.0,9137.0,11949.0,5092.0,6853.0,8576.0,9937.0,0,0,20928,33411,5,8055.0,0,1038
48706,2,2003,7,1,799,10,479,4,0,2.0,1,82174,0,6,2,3269.0,4435.0,6893.0,8221.0,4526.0,5761.0,8266.0,9388.0,0,0,20928,33411,5,7755.0,0,5392

train, test를 따로따로 fit_transform 적용할 때 
-> 알파벳 순서로 되다 보니 train/test에 있는 종류의 개수가 완벽히 같지 않을 수 있음
-> 처리가 될 때 알파벳 순서로 정렬 후 카테고리 번호를 부여하다 보니 같은 숫자로 매핑되지 않을 수 있다
-> 아예 처리시 alldata로 처리하는 것이 현명

In [14]:
alldata2.dtypes # 모든 column들의 datatype int, float 형으로 되어 있다

Auction                                int64
VehYear                                int64
VehicleAge                             int64
Make                                   int64
Model                                  int64
Trim                                   int64
SubModel                               int64
Color                                  int64
Transmission                           int64
WheelTypeID                          float64
WheelType                              int64
VehOdo                                 int64
Nationality                            int64
Size                                   int64
TopThreeAmericanName                   int64
MMRAcquisitionAuctionAveragePrice    float64
MMRAcquisitionAuctionCleanPrice      float64
MMRAcquisitionRetailAveragePrice     float64
MMRAcquisitonRetailCleanPrice        float64
MMRCurrentAuctionAveragePrice        float64
MMRCurrentAuctionCleanPrice          float64
MMRCurrentRetailAveragePrice         float64
MMRCurrentRetailCleanPrice           float64
PRIMEUNIT                              int64
AUCGUART                               int64
BYRNO                                  int64
VNZIP1                                 int64
VNST                                   int64
VehBCost                             float64
IsOnlineSale                           int64
WarrantyCost                           int64
dtype: object

<결측치>        
- None 값, 다른 값과는 다른 카테고리로 학습함
- None 값의 의미에 따라 다르게 다뤄야 함 (배경지식이 있을 때)
- 배경지식이 없을 때 >> 부스팅 모델     
    + 모델이 알아서 결측치를 만났을 때 결측치에 어떤 값이 들어가야지 판단   
    + 내부적으로 가장 점수 계산이 많이 되는 방향으로    
    + but overfitting 될 가능성 있음        
안전한 방법: 결측치 타 값들과 아예 다른 값으로 채우기

In [15]:
alldata2 = alldata2.fillna(-1) # 결측치 -1로 채워짐
alldata2

,Auction,VehYear,VehicleAge,Make,Model,Trim,SubModel,Color,Transmission,WheelTypeID,WheelType,VehOdo,Nationality,Size,TopThreeAmericanName,MMRAcquisitionAuctionAveragePrice,MMRAcquisitionAuctionCleanPrice,MMRAcquisitionRetailAveragePrice,MMRAcquisitonRetailCleanPrice,MMRCurrentAuctionAveragePrice,MMRCurrentAuctionCleanPrice,MMRCurrentRetailAveragePrice,MMRCurrentRetailCleanPrice,PRIMEUNIT,AUCGUART,BYRNO,VNZIP1,VNST,VehBCost,IsOnlineSale,WarrantyCost
0,0,2006,3,17,620,135,236,13,0,1.0,0,89046,2,5,3,8155.0,9829.0,11636.0,13600.0,7451.0,8552.0,11597.0,12409.0,2,2,21973,33619,5,7100.0,0,1113
1,0,2004,5,5,0,94,826,15,0,1.0,0,93593,0,4,0,6854.0,8383.0,10897.0,12572.0,7456.0,9222.0,11374.0,12791.0,2,2,19638,33619,5,7600.0,0,1053
2,0,2005,4,5,938,99,311,7,0,2.0,1,73807,0,5,0,3202.0,4760.0,6943.0,8457.0,4035.0,5557.0,7146.0,8702.0,2,2,19638,33619,5,4900.0,0,1389
3,0,2004,5,5,700,99,165,14,0,1.0,0,65617,0,0,0,1893.0,2675.0,4658.0,5690.0,1844.0,2646.0,4375.0,5518.0,2,2,19638,33619,5,4100.0,0,630
4,0,2005,4,6,389,129,55,14,1,2.0,1,69367,0,0,1,3913.0,5054.0,7723.0,8707.0,3247.0,4384.0,6739.0,7911.0,2,2,19638,33619,5,4000.0,0,1020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48702,2,2005,5,6,386,85,292,1,0,1.0,0,88645,0,2,1,5358.0,6836.0,8987.0,10905.0,5761.0,6965.0,9764.0,11395.0,2,2,20928,33411,5,7955.0,0,1633
48703,2,2007,3,29,241,9,198,5,0,2.0,1,81862,3,0,3,6849.0,7992.0,10999.0,12021.0,6856.0,8183.0,10283.0,11565.0,2,2,20928,33411,5,7035.0,0,594
48704,2,2006,4,14,912,23,210,1,0,2.0,1,82451,2,5,3,4662.0,5655.0,7972.0,9670.0,4833.0,5856.0,7871.0,9490.0,0,0,20928,33411,5,6335.0,0,594
48705,2,2005,5,17,620,136,223,14,0,1.0,0,75760,2,5,3,5953.0,8166.0,9137.0,11949.0,5092.0,6853.0,8576.0,9937.0,0,0,20928,33411,5,8055.0,0,1038
48706,2,2003,7,1,799,10,479,4,0,2.0,1,82174,0,6,2,3269.0,4435.0,6893.0,8221.0,4526.0,5761.0,8266.0,9388.0,0,0,20928,33411,5,7755.0,0,5392

In [16]:
# iloc 사용시: alldata2.iloc[데이터, 열]
train2 = alldata2[:len(train)] # 맨 앞의 데이터부터 트레인셋의 개수까지 가져옴
test2 = alldata2[len(train):]

display(train2.head(), test2.head())

,Auction,VehYear,VehicleAge,Make,Model,Trim,SubModel,Color,Transmission,WheelTypeID,WheelType,VehOdo,Nationality,Size,TopThreeAmericanName,MMRAcquisitionAuctionAveragePrice,MMRAcquisitionAuctionCleanPrice,MMRAcquisitionRetailAveragePrice,MMRAcquisitonRetailCleanPrice,MMRCurrentAuctionAveragePrice,MMRCurrentAuctionCleanPrice,MMRCurrentRetailAveragePrice,MMRCurrentRetailCleanPrice,PRIMEUNIT,AUCGUART,BYRNO,VNZIP1,VNST,VehBCost,IsOnlineSale,WarrantyCost
0,0,2006,3,17,620,135,236,13,0,1.0,0,89046,2,5,3,8155.0,9829.0,11636.0,13600.0,7451.0,8552.0,11597.0,12409.0,2,2,21973,33619,5,7100.0,0,1113
1,0,2004,5,5,0,94,826,15,0,1.0,0,93593,0,4,0,6854.0,8383.0,10897.0,12572.0,7456.0,9222.0,11374.0,12791.0,2,2,19638,33619,5,7600.0,0,1053
2,0,2005,4,5,938,99,311,7,0,2.0,1,73807,0,5,0,3202.0,4760.0,6943.0,8457.0,4035.0,5557.0,7146.0,8702.0,2,2,19638,33619,5,4900.0,0,1389
3,0,2004,5,5,700,99,165,14,0,1.0,0,65617,0,0,0,1893.0,2675.0,4658.0,5690.0,1844.0,2646.0,4375.0,5518.0,2,2,19638,33619,5,4100.0,0,630
4,0,2005,4,6,389,129,55,14,1,2.0,1,69367,0,0,1,3913.0,5054.0,7723.0,8707.0,3247.0,4384.0,6739.0,7911.0,2,2,19638,33619,5,4000.0,0,1020

,Auction,VehYear,VehicleAge,Make,Model,Trim,SubModel,Color,Transmission,WheelTypeID,WheelType,VehOdo,Nationality,Size,TopThreeAmericanName,MMRAcquisitionAuctionAveragePrice,MMRAcquisitionAuctionCleanPrice,MMRAcquisitionRetailAveragePrice,MMRAcquisitonRetailCleanPrice,MMRCurrentAuctionAveragePrice,MMRCurrentAuctionCleanPrice,MMRCurrentRetailAveragePrice,MMRCurrentRetailCleanPrice,PRIMEUNIT,AUCGUART,BYRNO,VNZIP1,VNST,VehBCost,IsOnlineSale,WarrantyCost
0,0,2005,4,24,464,7,165,14,0,1.0,0,85377,0,2,2,5032.0,6386.0,5935.0,7397.0,4905.0,6181.0,8557.0,9752.0,2,2,18881,30212,6,6500.0,0,2152
1,0,2005,4,3,597,56,248,14,0,1.0,0,61873,0,5,2,4502.0,5685.0,5362.0,6640.0,4645.0,5710.0,7562.0,9296.0,2,2,18111,30212,6,6300.0,0,1118
2,0,2006,3,5,270,6,438,14,0,1.0,0,69283,0,6,0,10244.0,13041.0,11564.0,14584.0,10883.0,12166.0,15340.0,16512.0,2,2,18111,30212,6,9700.0,0,1215
3,0,2002,7,25,540,52,239,4,0,1.0,0,87889,0,5,2,2558.0,3542.0,3263.0,4325.0,2928.0,3607.0,5725.0,6398.0,2,2,18881,30212,6,4150.0,0,1933
4,0,2007,2,10,42,33,27,2,0,-1.0,3,73432,2,0,3,5013.0,6343.0,5914.0,7350.0,5013.0,6343.0,5914.0,7350.0,2,2,18111,30212,6,4100.0,0,920

In [17]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_jobs = -1) # njobs = -1 모든 cpu 병렬로 활용
rf.fit(train2, train['IsBadBuy'])
# result = rf.predict(test2)

# 99%의 데이터 -> 정답, 1번일 때의 확률의 더 중요
# IsBadBuy > 사기를 당할 확률이 더 중요
# 각 데이터별로 확률값, 정도에 대해 분류
# classification -> 분류 기준, threshold 조정 들 고려하
result = rf.predict_proba(test2)
result

array([[0.93, 0.07],
       [0.94, 0.06],
       [0.98, 0.02],
       ...,
       [0.93, 0.07],
       [0.88, 0.12],
       [0.9 , 0.1 ]])

In [18]:
sub = pd.read_csv('../input/DontGetKicked/example_entry.csv')
sub

        RefId  IsBadBuy
0       73015         0
1       73016         0
2       73017         0
3       73018         0
4       73019         0
...       ...       ...
48702  121742         0
48703  121743         0
48704  121744         0
48705  121745         0
48706  121746         0

[48707 rows x 2 columns]

In [19]:
sub['IsBadBuy'] = result[:, 1]
sub

        RefId  IsBadBuy
0       73015      0.07
1       73016      0.06
2       73017      0.02
3       73018      0.14
4       73019      0.81
...       ...       ...
48702  121742      0.12
48703  121743      0.05
48704  121744      0.07
48705  121745      0.12
48706  121746      0.10

[48707 rows x 2 columns]

In [20]:
sub.to_csv('submission_baseline.csv', index = False)